[project]
name = "mkv-episode-matcher"
description = "The MKV Episode Matcher is a tool for identifying TV series episodes from MKV files and renaming the files accordingly."
authors = [
  { name="Jonathan Sakkos", email="jonathansakkos@protonmail.com" },
]
readme = "README.md"
dynamic = ["version"]

requires-python = ">=3.8"
license = "MIT"
[build-system]
requires = ["hatchling",
  "requests",
    "loguru",
    "pillow",
    "imagehash",
    "configparser",
    "tmdb_client",
    "pytesseract",
    "opensubtitlescom",
]
build-backend = "hatchling.build"
dependencies = [
  "requests",
    "loguru",
    "pillow",
    "imagehash",
    "configparser",
    "tmdb_client",
    "pytesseract",
    "opensubtitlescom",
]
[tool]

[project.scripts]
mkv-match = "mkv_episode_matcher:__main__"

[tool.ruff.format]
preview = true
quote-style = "single"

[tool.ruff.lint]
preview = true
extend-select = ["C901"]

[tool.ruff.lint.extend-per-file-ignores]
"docs/.hooks/*" = ["INP001", "T201"]

[tool.ruff.lint.isort]
known-first-party = ["foo", "bar"]

[tool.hatch.version]
path = "mkv_episode_matcher/__init__.py"